name: Repository Updater

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: ["update"]

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update repository
    steps:
      - name: 🚀 Run Repository Updater
        uses: hassio-addons/repository-updater@v1.3.0
        with:
          addon: ${{ github.event.client_payload.addon }}
          repository: ${{ github.repository }}
          token: ${{ secrets.DISPATCH_TOKEN }}